### ISSUE TITLE
Digital filter critical frequencies error when openning .h5 file

### ISSUE THREAD

**Issue by Andrianarivelo** [esedaghatnejad/psort#8]
Hello, 

I'm trying to open an .h5 files with psort, the file contains ch_data, ch_time and sample_rate. They are from in-vivo cell-attached recordings, my sample rate is 10000Hz. When opening the file I keep getting this error   
```raise ValueError("Digital filter critical frequencies "
ValueError: Digital filter critical frequencies must be 0 < Wn < 1
```
Can you help me solving the problem ?

**Comment by esedaghatnejad** [comment]
Thanks for your interest in psort.
I checked the file that you attached to your email:
`EphysDataPerSession_2022.04.11_000_locomotionEphysMotor60sec__psort.h5`

Unfortunately, I got errors either using psort, or just in the plain Python environment.
Looking at the error message it appears that your file is not a standard H5 file. The problem is not with the psort software, but it is from the backend libraries and specially the hdf5io library. 

To help you resolve the issue, I need to make sure that you can open your file in a Python environment.
Can you provide me a code that can simply open the file and print the content of the file?

**Comment by Andrianarivelo** [comment]
I actually managed to solve the problem by rescaling my recording to 20kHz using interpolation. Thanks

**Comment by esedaghatnejad** [comment]
Glad to see your problem got resolved. Let me know if you faced any further issues.
